### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [sophmintaii/UCU_2term_homework#1]
Все зрозуміло але що саме за дані Ви використовуєте?
Тема: Аналіз впливу психічних розладів на здійснення суїцидів у різних вікових групах.

**Comment by sophmintaii** [comment]
Дякую за зауваження, додала інформацію на сторінку wiki.
Під час виконання роботи я планую використовувати дані з сайтів data.world (Наприклад, наступні датасети: [Suicide Line Listing By Age Group And Gender 2012-2018](https://data.world/cityofaustin/cxhd-bvc3), [Deaths from Suicide](https://data.world/datagov-uk/787845cf-fbc7-4fae-a7de-eb231d35e2c9)), можливо, з вебсайту [APA](https://www.apa.org/pubs/databases/). Також в моїх планах створити опитування і за допомогою Google Sheets API отримати його результати з гугл-таблиці.
