### ISSUE TITLE
ДЗ3,4,5

### ISSUE THREAD

**Issue by anrom7** [sophmintaii/UCU_2term_homework#3]
Діаграма структури даних - що це й навіщо.
Нtml та графіки генеруються при кожному запуску?

**Comment by sophmintaii** [comment]
1) Діаграма структури даних створена для наявності. Окрім того, вимога її створити була підпунктом 3.5 третього домашнього завдання.
2) Так, у відео-презентації було сказано, що вони генеруються при запуску і це займає певний час.
